DECLARE @DB_NAME VARCHAR(10),
@SQLSCRIPT VARCHAR(1000),
@TABLE_NAME VARCHAR(10),
@IS_DROP BOOLEAN;

SET @IS_DROP = false;
SET @DB_NAME = 'myDB';

SET @TABLE_NAME = 'EMAIL_TYPE'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	DROP TABLE @TABLE_NAME
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						TYPE VARCHAR(255) NOT NULL,
						DESCRIPTION VARCHAR(255) NOT NULL,
						PRIMARY KEY (ID)
					)'
END 

SET @TABLE_NAME = 'EMAIL'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	DROP TABLE @TABLE_NAME
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						EMAIL_TYPE_ID INT NOT NULL,
						EMAIL_ADDRESS VARCHAR(255) NOT NULL,
						PRIMARY KEY (ID)
					)'
END 

SET @TABLE_NAME = 'USER';
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	DROP TABLE @TABLE_NAME
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						FIRSTNAME VARCHAR(255) NOT NULL,
						LASTNAME VARCHAR(255) NOT NULL,
					'
		
END;